name: build

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["update"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9.0.4
      - name: install
        run: pnpm install
      - name: main
        run: pnpm main
      - name: build
        run: pnpm run build
      - name: test
        run: pnpm test
      - name: main:build
        run: pnpm run main:build
